package laporan;
import fungsi.koneksiDB;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

public class DlgRL4ASebab extends javax.swing.JDialog {
    private final validasi Valid=new validasi();
    private final Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,ps2,ps3;
    private ResultSet rs,rs2;
    private StringBuilder htmlContent;
    private int jam0s23p=0,jam0s23l=0,hr1s7p=0,hr1s7l=0,hr8s28p=0,hr8s28l=0,hr29s3p=0,hr29s3l=0,bl3s5p=0,bl3s5l=0,
                bl6s11p=0,bl6s11l=0,th1s4p=0,th1s4l=0,th5s9l=0,th5s9p=0,th10s14l=0,th10s14p=0,th15s19l=0,th15s19p=0,
                th20s24l=0,th20s24p=0,th25s29l=0,th25s29p=0,th30s34l=0,th30s34p=0,th35s39l=0,th35s39p=0,th40s44l=0,th40s44p=0,
                th45s49l=0,th45s49p=0,th50s54l=0,th50s54p=0,th55s59l=0,th55s59p=0,th60s64l=0,th60s64p=0,th65s69l=0,th65s69p=0,
                th70s74l=0,th70s74p=0,th75s79l=0,th75s79p=0,th80s84l=0,th80s84p=0,th85s100l=0,th85s100p=0,mati=0;
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgRL4ASebab(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        LoadHTML1.setEditable(true);
        LoadHTML1.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML1.setDocument(doc);
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    private int i=0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        btnCari = new widget.Button();
        label9 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        TabRawat = new javax.swing.JTabbedPane();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();
        Scroll1 = new widget.ScrollPane();
        LoadHTML1 = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ RL 4A Sebab Data Keadaan Morbiditas Pasien Rawat Inap Kemkes ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelisi1.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi1.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl2);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(100, 30));
        panelisi1.add(label9);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        TabRawat.setBackground(new java.awt.Color(255, 255, 253));
        TabRawat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        TabRawat.setForeground(new java.awt.Color(50, 50, 50));
        TabRawat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TabRawat.setName("TabRawat"); // NOI18N
        TabRawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabRawatMouseClicked(evt);
            }
        });

        Scroll.setBorder(null);
        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        TabRawat.addTab("Berdasar Tanggal Masuk", Scroll);

        Scroll1.setBorder(null);
        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        LoadHTML1.setBorder(null);
        LoadHTML1.setName("LoadHTML1"); // NOI18N
        Scroll1.setViewportView(LoadHTML1);

        TabRawat.addTab("Berdasar Tanggal Keluar", Scroll1);

        internalFrame1.add(TabRawat, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            
            File g = new File("file2.css");            
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(
                    ".isi td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi2 td{font: 11px tahoma;height:12px;background: #ffffff;color:#323232;}"+                    
                    ".isi3 td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
            );
            bg.close();
            
            File f = new File("rl4a.html");            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));
            if(TabRawat.getSelectedIndex()==0){
                bw.write(LoadHTML.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                                "<tr class='isi2'>"+
                                    "<td valign='top' align='center'>"+
                                        "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                        akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                        akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+
                                        "<font size='2' face='Tahoma'>DATA KEADAAN MORBIDITAS PASIEN RAWAT INAP RUMAH SAKIT PENYEBAB KECELAKAN<br>PERIODE "+Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem()+"<br><br></font>"+        
                                    "</td>"+
                               "</tr>"+
                            "</table>")
                );
                bw.close();
            }else if(TabRawat.getSelectedIndex()==1){
                bw.write(LoadHTML1.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                                "<tr class='isi2'>"+
                                    "<td valign='top' align='center'>"+
                                        "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                        akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                        akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+
                                        "<font size='2' face='Tahoma'>DATA KEADAAN MORBIDITAS PASIEN RAWAT INAP RUMAH SAKIT PENYEBAB KECELAKAN<br>PERIODE "+Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem()+"<br><br></font>"+        
                                    "</td>"+
                               "</tr>"+
                            "</table>")
                );
                bw.close();
            }                
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : "+e);
        }     
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,Tgl2,BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint,Tgl1);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        if(TabRawat.getSelectedIndex()==0){
            prosesCari();
        }else if(TabRawat.getSelectedIndex()==1){
            prosesCari2();
        }
}//GEN-LAST:event_btnCariActionPerformed

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl2, BtnPrint);
        }
}//GEN-LAST:event_btnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prosesCari();
    }//GEN-LAST:event_formWindowOpened

    private void TabRawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabRawatMouseClicked
        if(TabRawat.getSelectedIndex()==0){
            prosesCari();
        }else if(TabRawat.getSelectedIndex()==1){
            prosesCari2();
        }
    }//GEN-LAST:event_TabRawatMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRL4ASebab dialog = new DlgRL4ASebab(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.editorpane LoadHTML1;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private javax.swing.JTabbedPane TabRawat;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    private void prosesCari() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%' rowspan='3'>No.Urut</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='3'>No.Daftar Terperinci</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='18%' rowspan='3'>Golongan Sebab Penyakit</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='55%' colspan='50'>Jumlah Pasien Hidup dan Mati menurut Golongan Umur & Jenis Kelamin</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' colspan='2'>Pasien Keluar (Hidup & Mati) Menurut Jenis Kelamin</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='3'>Jumlah Pasien Keluar Hidup (54+55)</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='3'>Jumlah Pasien Keluar Mati</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>&lt;1 Jam</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-23 Jam</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-7 Hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>8-28 Hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>29 hari- &gt;3 Bl</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>3- &gt;6 Bl</td>"+    
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>6-11 Bl</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-4 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>5-9 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>10-14 Th</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>15-19 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>20-24 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>25-29 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>30-34 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>35-39 Th</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>40-44 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>45-49 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>50-54 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>55-59 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>60-64 Th</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>65-69 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>70-74 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>75-79 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>80-84 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>&ge;85 Th</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>LK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>PR</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>1</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>2</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>3</td>"+
                        //start
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>4</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>5</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>6</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>7</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>8</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>9</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>10</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>11</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>12</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>13</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>14</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>15</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>16</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>17</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>18</td>"+                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>19</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>20</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>21</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>22</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>23</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>24</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>25</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>26</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>27</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>28</td>"+                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>29</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>30</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>31</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>32</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>33</td>"+ 
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>34</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>35</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>36</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>37</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>38</td>"+                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>39</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>40</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>41</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>42</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>43</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>44</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>45</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>46</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>47</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>48</td>"+                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>49</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>50</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>51</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>52</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>53</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>54</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>55</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>56</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>57</td>"+
                "</tr>"
            );              
            ps=koneksi.prepareStatement("select diagnosa_pasien.kd_penyakit,SUBSTRING(penyakit.nm_penyakit,1,80) as nm_penyakit from diagnosa_pasien inner join penyakit "+
                    "inner join reg_periksa on diagnosa_pasien.kd_penyakit=penyakit.kd_penyakit and reg_periksa.no_rawat=diagnosa_pasien.no_rawat "+
                    "where diagnosa_pasien.status='Ranap' and reg_periksa.tgl_registrasi between ? and ? "+
                    " group by diagnosa_pasien.kd_penyakit order by diagnosa_pasien.kd_penyakit");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    jam0s23p=0;jam0s23l=0;hr1s7p=0;hr1s7l=0;hr8s28p=0;hr8s28l=0;hr29s3p=0;hr29s3l=0;bl3s5p=0;bl3s5l=0;
                    bl6s11p=0;bl6s11l=0;th1s4p=0;th1s4l=0;th5s9l=0;th5s9p=0;th10s14l=0;th10s14p=0;th15s19l=0;th15s19p=0;
                    th20s24l=0;th20s24p=0;th25s29l=0;th25s29p=0;th30s34l=0;th30s34p=0;th35s39l=0;th35s39p=0;th40s44l=0;th40s44p=0;
                    th45s49l=0;th45s49p=0;th50s54l=0;th50s54p=0;th55s59l=0;th55s59p=0;th60s64l=0;th60s64p=0;th65s69l=0;th65s69p=0;
                    th70s74l=0;th70s74p=0;th75s79l=0;th75s79p=0;th80s84l=0;th80s84p=0;th85s100l=0;th85s100p=0;mati=0;
                    ps2=koneksi.prepareStatement(
                            "select diagnosa_pasien.kd_penyakit,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "where diagnosa_pasien.status='Ranap' "+
                            "and reg_periksa.tgl_registrasi between ? and ? and diagnosa_pasien.kd_penyakit=?");
                    try {
                        ps2.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps2.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps2.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps2.executeQuery();
                        while(rs2.next()){
                            if(rs2.getString("sttsumur").equals("Hr")){
                                if((rs2.getInt("umurdaftar")>=0)&&(rs2.getInt("umurdaftar")<1)){
                                    if(rs2.getString("jk").equals("L")){
                                        jam0s23l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        jam0s23p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=1)&&(rs2.getInt("umurdaftar")<=7)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr1s7l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr1s7p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=8)&&(rs2.getInt("umurdaftar")<=31)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr8s28l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr8s28p++;
                                    }
                                }
                            }else if(rs2.getString("sttsumur").equals("Bl")){
                                if((rs2.getInt("umurdaftar")>=1)&&(rs2.getInt("umurdaftar")<3)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr29s3l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr29s3p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=3)&&(rs2.getInt("umurdaftar")<6)){
                                    if(rs2.getString("jk").equals("L")){
                                        bl3s5l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        bl3s5p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=6)&&(rs2.getInt("umurdaftar")<=11)){
                                    if(rs2.getString("jk").equals("L")){
                                        bl6s11l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        bl6s11p++;
                                    }
                                }
                            }else if(rs2.getString("sttsumur").equals("Th")){
                                if((rs2.getInt("umurdaftar")>=1)&&(rs2.getInt("umurdaftar")<=4)){
                                    if(rs2.getString("jk").equals("L")){
                                        th1s4l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th1s4p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=5)&&(rs2.getInt("umurdaftar")<=9)){
                                    if(rs2.getString("jk").equals("L")){
                                        th5s9l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th5s9p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=10)&&(rs2.getInt("umurdaftar")<=14)){
                                    if(rs2.getString("jk").equals("L")){
                                        th10s14l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th10s14p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=15)&&(rs2.getInt("umurdaftar")<=19)){
                                    if(rs2.getString("jk").equals("L")){
                                        th15s19l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th15s19p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=20)&&(rs2.getInt("umurdaftar")<=24)){
                                    if(rs2.getString("jk").equals("L")){
                                        th20s24l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th20s24p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=25)&&(rs2.getInt("umurdaftar")<=29)){
                                    if(rs2.getString("jk").equals("L")){
                                        th25s29l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th25s29p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=30)&&(rs2.getInt("umurdaftar")<=34)){
                                    if(rs2.getString("jk").equals("L")){
                                        th30s34l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th30s34p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=35)&&(rs2.getInt("umurdaftar")<=39)){
                                    if(rs2.getString("jk").equals("L")){
                                        th35s39l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th35s39p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=40)&&(rs2.getInt("umurdaftar")<=44)){
                                    if(rs2.getString("jk").equals("L")){
                                        th40s44l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th40s44p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=49)){
                                    if(rs2.getString("jk").equals("L")){
                                        th45s49l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th45s49p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=50)&&(rs2.getInt("umurdaftar")<=54)){
                                    if(rs2.getString("jk").equals("L")){
                                        th50s54l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th50s54p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=55)&&(rs2.getInt("umurdaftar")<=59)){
                                    if(rs2.getString("jk").equals("L")){
                                        th55s59l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th55s59p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=60)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th60s64l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th60s64p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=65)&&(rs2.getInt("umurdaftar")<=69)){
                                    if(rs2.getString("jk").equals("L")){
                                        th65s69l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th65s69p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=70)&&(rs2.getInt("umurdaftar")<=74)){
                                    if(rs2.getString("jk").equals("L")){
                                        th70s74l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th70s74p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=75)&&(rs2.getInt("umurdaftar")<=79)){
                                    if(rs2.getString("jk").equals("L")){
                                        th75s79l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th75s79p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=80)&&(rs2.getInt("umurdaftar")<=84)){
                                    if(rs2.getString("jk").equals("L")){
                                        th80s84l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th80s84p++;
                                    }
                                }else if(rs2.getInt("umurdaftar")>=85){
                                    if(rs2.getString("jk").equals("L")){
                                        th85s100l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th85s100p++;
                                    }
                                }
                            }
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgRL4A.prosesCari() 1 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    
                    ps3=koneksi.prepareStatement(
                            "select count(pasien_mati.no_rkm_medis) "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join pasien_mati "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and pasien_mati.no_rkm_medis=pasien.no_rkm_medis where diagnosa_pasien.status='Ranap' "+
                            "and reg_periksa.tgl_registrasi between ? and ? and diagnosa_pasien.kd_penyakit=? "+
                            "group by diagnosa_pasien.kd_penyakit");
                    try {
                        ps3.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps3.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps3.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps3.executeQuery();
                        while(rs2.next()){
                            mati=rs2.getInt(1);
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgRL4A.prosesCari() 2 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kd_penyakit")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                                    //1
                            "<td valign='middle' align='center'>0</td>"+ //< 1jam l
                            "<td valign='middle' align='center'>0</td>"+ //< 1jam p
                            "<td valign='middle' align='center'>"+jam0s23l+"</td>"+ // 1hari L
                            "<td valign='middle' align='center'>"+jam0s23p+"</td>"+ // 1hari P
                            "<td valign='middle' align='center'>"+hr1s7l+"</td>"+ // 1-7hari L 
                            "<td valign='middle' align='center'>"+hr1s7p+"</td>"+ //1-7hari P 
                            "<td valign='middle' align='center'>"+hr8s28l+"</td>"+ // 8-28hari L 
                            "<td valign='middle' align='center'>"+hr8s28p+"</td>"+ // 8-28hari P 
                            "<td valign='middle' align='center'>"+hr29s3l+"</td>"+ // 29hari - 3bulan L 
                            "<td valign='middle' align='center'>"+hr29s3p+"</td>"+ // 29hari - 3bulan P 
                                    //2
                            "<td valign='middle' align='center'>"+bl3s5l+"</td>"+ //3-6bulan L
                            "<td valign='middle' align='center'>"+bl3s5p+"</td>"+ //3-6bulan P
                            "<td valign='middle' align='center'>"+bl6s11l+"</td>"+ //6-11bulan L
                            "<td valign='middle' align='center'>"+bl6s11p+"</td>"+ //6-11bulan P
                            "<td valign='middle' align='center'>"+th1s4l+"</td>"+ //1-4tahun L
                            "<td valign='middle' align='center'>"+th1s4p+"</td>"+ //1-4tahun P 
                            "<td valign='middle' align='center'>"+th5s9l+"</td>"+ //5-9tahun L
                            "<td valign='middle' align='center'>"+th5s9p+"</td>"+ //5-9tahun P
                            "<td valign='middle' align='center'>"+th10s14p+"</td>"+ //10-14tahun L
                            "<td valign='middle' align='center'>"+th10s14p+"</td>"+ //10-14tahun P    
                                    //3
                            "<td valign='middle' align='center'>"+th15s19l+"</td>"+ //15 th L
                            "<td valign='middle' align='center'>"+th15s19p+"</td>"+ //15 th P
                            "<td valign='middle' align='center'>"+th20s24l+"</td>"+ //20 th L
                            "<td valign='middle' align='center'>"+th20s24p+"</td>"+ //20 th P
                            "<td valign='middle' align='center'>"+th25s29l+"</td>"+ //25
                            "<td valign='middle' align='center'>"+th25s29p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th30s34l+"</td>"+ //30
                            "<td valign='middle' align='center'>"+th30s34p+"</td>"+  
                            "<td valign='middle' align='center'>"+th35s39l+"</td>"+ //35
                            "<td valign='middle' align='center'>"+th35s39p+"</td>"+ 
                                    //4
                            "<td valign='middle' align='center'>"+th40s44l+"</td>"+
                            "<td valign='middle' align='center'>"+th40s44p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th45s49l+"</td>"+
                            "<td valign='middle' align='center'>"+th45s49p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th50s54l+"</td>"+
                            "<td valign='middle' align='center'>"+th50s54p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th55s59l+"</td>"+
                            "<td valign='middle' align='center'>"+th55s59p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th60s64l+"</td>"+
                            "<td valign='middle' align='center'>"+th60s64p+"</td>"+
                                    //5
                            "<td valign='middle' align='center'>"+th65s69l+"</td>"+
                            "<td valign='middle' align='center'>"+th65s69p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th70s74l+"</td>"+
                            "<td valign='middle' align='center'>"+th70s74p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th75s79l+"</td>"+
                            "<td valign='middle' align='center'>"+th75s79p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th80s84l+"</td>"+
                            "<td valign='middle' align='center'>"+th80s84p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th85s100l+"</td>"+
                            "<td valign='middle' align='center'>"+th85s100p+"</td>"+
                                    //
                            "<td valign='middle' align='center'>"+(jam0s23l+hr1s7l+hr8s28l+hr29s3l+bl3s5l+bl6s11l+th1s4l+th5s9l+th10s14l+th15s19l+
                                    th20s24l+th25s29l+th30s34l+th35s39l+th40s44l+th45s49l+th50s54l+th55s59l+th60s64l+th65s69l+th70s74l+th75s79l+th80s84l+th85s100l)+"</td>"+
                            "<td valign='middle' align='center'>"+(jam0s23p+hr1s7p+hr8s28p+hr29s3p+bl3s5p+bl6s11p+th1s4p+th5s9p+th10s14p+th15s19p+
                                    th20s24p+th25s29p+th30s34p+th35s39p+th40s44p+th45s49p+th50s54p+th55s59p+th60s64p+th65s69p+th70s74p+th75s79p+th80s84p+th85s100p)+"</td>"+
                            "<td valign='middle' align='center'>"+(jam0s23p+jam0s23l+hr1s7p+hr1s7l+hr8s28p+hr8s28l+hr29s3p+hr29s3l+bl3s5p+bl3s5l+
                            bl6s11p+bl6s11l+th1s4p+th1s4l+th5s9l+th5s9p+th10s14l+th10s14p+th15s19l+th15s19p+
                            th20s24l+th20s24p+th25s29l+th25s29p+th30s34l+th30s34p+th35s39l+th35s39p+th40s44l+th40s44p+
                            th45s49l+th45s49p+th50s54l+th50s54p+th55s59l+th55s59p+th60s64l+th60s64p+th65s69l+th65s69p+
                            th70s74l+th70s74p+th75s79l+th75s79p+th80s84l+th80s84p+th85s100l+th85s100p-mati)+"</td>"+
                            "<td valign='middle' align='center'>"+mati+"</td>"+
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgRL4A.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgRL4A.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());
        
    }
    
    private void prosesCari2() {
       this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%' rowspan='3'>No.Urut</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='3'>No.Daftar Terperinci</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='18%' rowspan='3'>Golongan Sebab Penyakit</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='55%' colspan='50'>Jumlah Pasien Hidup dan Mati menurut Golongan Umur & Jenis Kelamin</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' colspan='2'>Pasien Keluar (Hidup & Mati) Menurut Jenis Kelamin</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='3'>Jumlah Pasien Keluar Hidup (54+55)</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='3'>Jumlah Pasien Keluar Mati</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>&lt;1 Jam</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-23 Jam</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-7 Hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>8-28 Hr</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>29 hari- &gt;3 Bl</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>3- &gt;6 Bl</td>"+    
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>6-11 Bl</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>1-4 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>5-9 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>10-14 Th</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>15-19 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>20-24 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>25-29 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>30-34 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>35-39 Th</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>40-44 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>45-49 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>50-54 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>55-59 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>60-64 Th</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>65-69 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>70-74 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>75-79 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>80-84 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>&ge;85 Th</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>LK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>PR</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>1</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>2</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>3</td>"+
                        //start
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>4</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>5</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>6</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>7</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>8</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>9</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>10</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>11</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>12</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>13</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>14</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>15</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>16</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>17</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>18</td>"+                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>19</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>20</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>21</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>22</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>23</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>24</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>25</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>26</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>27</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>28</td>"+                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>29</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>30</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>31</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>32</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>33</td>"+ 
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>34</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>35</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>36</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>37</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>38</td>"+                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>39</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>40</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>41</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>42</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>43</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>44</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>45</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>46</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>47</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>48</td>"+                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>49</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>50</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>51</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>52</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>53</td>"+
                        //
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>54</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>55</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>56</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>57</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("select diagnosa_pasien.kd_penyakit,SUBSTRING(penyakit.nm_penyakit,1,80) as nm_penyakit from diagnosa_pasien inner join penyakit "+
                    "inner join reg_periksa inner join kamar_inap on diagnosa_pasien.kd_penyakit=penyakit.kd_penyakit and reg_periksa.no_rawat=diagnosa_pasien.no_rawat "+
                    "and kamar_inap.no_rawat=reg_periksa.no_rawat where diagnosa_pasien.status='Ranap' and diagnosa_pasien.prioritas='1' and "+
                    "kamar_inap.tgl_keluar between ? and ? "+
                    "group by diagnosa_pasien.kd_penyakit order by diagnosa_pasien.kd_penyakit");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    jam0s23p=0;jam0s23l=0;hr1s7p=0;hr1s7l=0;hr8s28p=0;hr8s28l=0;hr29s3p=0;hr29s3l=0;bl3s5p=0;bl3s5l=0;
                    bl6s11p=0;bl6s11l=0;th1s4p=0;th1s4l=0;th5s9l=0;th5s9p=0;th10s14l=0;th10s14p=0;th15s19l=0;th15s19p=0;
                    th20s24l=0;th20s24p=0;th25s29l=0;th25s29p=0;th30s34l=0;th30s34p=0;th35s39l=0;th35s39p=0;th40s44l=0;th40s44p=0;
                    th45s49l=0;th45s49p=0;th50s54l=0;th50s54p=0;th55s59l=0;th55s59p=0;th60s64l=0;th60s64p=0;th65s69l=0;th65s69p=0;
                    th70s74l=0;th70s74p=0;th75s79l=0;th75s79p=0;th80s84l=0;th80s84p=0;th85s100l=0;th85s100p=0;mati=0;
                    ps2=koneksi.prepareStatement(
                            "select diagnosa_pasien.kd_penyakit,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join kamar_inap "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and kamar_inap.no_rawat=reg_periksa.no_rawat where diagnosa_pasien.status='Ranap' "+
                            "and kamar_inap.tgl_keluar between ? and ? and diagnosa_pasien.kd_penyakit=?");
                    try {
                        ps2.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps2.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps2.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps2.executeQuery();
                        while(rs2.next()){
                            if(rs2.getString("sttsumur").equals("Hr")){
                                if((rs2.getInt("umurdaftar")>=0)&&(rs2.getInt("umurdaftar")<1)){
                                    if(rs2.getString("jk").equals("L")){
                                        jam0s23l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        jam0s23p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=1)&&(rs2.getInt("umurdaftar")<=7)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr1s7l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr1s7p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=8)&&(rs2.getInt("umurdaftar")<=31)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr8s28l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr8s28p++;
                                    }
                                }
                            }else if(rs2.getString("sttsumur").equals("Bl")){
                                if((rs2.getInt("umurdaftar")>=1)&&(rs2.getInt("umurdaftar")<3)){
                                    if(rs2.getString("jk").equals("L")){
                                        hr29s3l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        hr29s3p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=3)&&(rs2.getInt("umurdaftar")<6)){
                                    if(rs2.getString("jk").equals("L")){
                                        bl3s5l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        bl3s5p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=6)&&(rs2.getInt("umurdaftar")<=11)){
                                    if(rs2.getString("jk").equals("L")){
                                        bl6s11l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        bl6s11p++;
                                    }
                                }
                            }else if(rs2.getString("sttsumur").equals("Th")){
                                if((rs2.getInt("umurdaftar")>=1)&&(rs2.getInt("umurdaftar")<=4)){
                                    if(rs2.getString("jk").equals("L")){
                                        th1s4l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th1s4p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=5)&&(rs2.getInt("umurdaftar")<=9)){
                                    if(rs2.getString("jk").equals("L")){
                                        th5s9l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th5s9p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=10)&&(rs2.getInt("umurdaftar")<=14)){
                                    if(rs2.getString("jk").equals("L")){
                                        th10s14l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th10s14p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=15)&&(rs2.getInt("umurdaftar")<=19)){
                                    if(rs2.getString("jk").equals("L")){
                                        th15s19l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th15s19p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=20)&&(rs2.getInt("umurdaftar")<=24)){
                                    if(rs2.getString("jk").equals("L")){
                                        th20s24l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th20s24p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=25)&&(rs2.getInt("umurdaftar")<=29)){
                                    if(rs2.getString("jk").equals("L")){
                                        th25s29l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th25s29p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=30)&&(rs2.getInt("umurdaftar")<=34)){
                                    if(rs2.getString("jk").equals("L")){
                                        th30s34l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th30s34p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=35)&&(rs2.getInt("umurdaftar")<=39)){
                                    if(rs2.getString("jk").equals("L")){
                                        th35s39l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th35s39p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=40)&&(rs2.getInt("umurdaftar")<=44)){
                                    if(rs2.getString("jk").equals("L")){
                                        th40s44l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th40s44p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=45)&&(rs2.getInt("umurdaftar")<=49)){
                                    if(rs2.getString("jk").equals("L")){
                                        th45s49l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th45s49p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=50)&&(rs2.getInt("umurdaftar")<=54)){
                                    if(rs2.getString("jk").equals("L")){
                                        th50s54l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th50s54p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=55)&&(rs2.getInt("umurdaftar")<=59)){
                                    if(rs2.getString("jk").equals("L")){
                                        th55s59l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th55s59p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=60)&&(rs2.getInt("umurdaftar")<=64)){
                                    if(rs2.getString("jk").equals("L")){
                                        th60s64l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th60s64p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=65)&&(rs2.getInt("umurdaftar")<=69)){
                                    if(rs2.getString("jk").equals("L")){
                                        th65s69l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th65s69p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=70)&&(rs2.getInt("umurdaftar")<=74)){
                                    if(rs2.getString("jk").equals("L")){
                                        th70s74l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th70s74p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=75)&&(rs2.getInt("umurdaftar")<=79)){
                                    if(rs2.getString("jk").equals("L")){
                                        th75s79l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th75s79p++;
                                    }
                                }else if((rs2.getInt("umurdaftar")>=80)&&(rs2.getInt("umurdaftar")<=84)){
                                    if(rs2.getString("jk").equals("L")){
                                        th80s84l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th80s84p++;
                                    }
                                }else if(rs2.getInt("umurdaftar")>=85){
                                    if(rs2.getString("jk").equals("L")){
                                        th85s100l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        th85s100p++;
                                    }
                                }
                            }
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgRL4A.prosesCari() 1 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    
                    ps3=koneksi.prepareStatement(
                            "select count(pasien_mati.no_rkm_medis) "+
                            "from diagnosa_pasien inner join reg_periksa inner join pasien inner join pasien_mati inner join kamar_inap "+
                            "on reg_periksa.no_rawat=diagnosa_pasien.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis "+
                            "and pasien_mati.no_rkm_medis=pasien.no_rkm_medis where diagnosa_pasien.status='Ranap' and kamar_inap.no_rawat=reg_periksa.no_rawat "+
                            "and kamar_inap.tgl_keluar between ? and ? and diagnosa_pasien.kd_penyakit=? "+
                            "group by diagnosa_pasien.kd_penyakit");
                    try {
                        ps3.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps3.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps3.setString(3,rs.getString("kd_penyakit"));
                        rs2=ps3.executeQuery();
                        while(rs2.next()){
                            mati=rs2.getInt(1);
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgRL4A.prosesCari() 2 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kd_penyakit")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                                    //1
                            "<td valign='middle' align='center'>0</td>"+ //< 1jam l
                            "<td valign='middle' align='center'>0</td>"+ //< 1jam p
                            "<td valign='middle' align='center'>"+jam0s23l+"</td>"+ // 1hari L
                            "<td valign='middle' align='center'>"+jam0s23p+"</td>"+ // 1hari P
                            "<td valign='middle' align='center'>"+hr1s7l+"</td>"+ // 1-7hari L 
                            "<td valign='middle' align='center'>"+hr1s7p+"</td>"+ //1-7hari P 
                            "<td valign='middle' align='center'>"+hr8s28l+"</td>"+ // 8-28hari L 
                            "<td valign='middle' align='center'>"+hr8s28p+"</td>"+ // 8-28hari P 
                            "<td valign='middle' align='center'>"+hr29s3l+"</td>"+ // 29hari - 3bulan L 
                            "<td valign='middle' align='center'>"+hr29s3p+"</td>"+ // 29hari - 3bulan P 
                                    //2
                            "<td valign='middle' align='center'>"+bl3s5l+"</td>"+ //3-6bulan L
                            "<td valign='middle' align='center'>"+bl3s5p+"</td>"+ //3-6bulan P
                            "<td valign='middle' align='center'>"+bl6s11l+"</td>"+ //6-11bulan L
                            "<td valign='middle' align='center'>"+bl6s11p+"</td>"+ //6-11bulan P
                            "<td valign='middle' align='center'>"+th1s4l+"</td>"+ //1-4tahun L
                            "<td valign='middle' align='center'>"+th1s4p+"</td>"+ //1-4tahun P 
                            "<td valign='middle' align='center'>"+th5s9l+"</td>"+ //5-9tahun L
                            "<td valign='middle' align='center'>"+th5s9p+"</td>"+ //5-9tahun P
                            "<td valign='middle' align='center'>"+th10s14p+"</td>"+ //10-14tahun L
                            "<td valign='middle' align='center'>"+th10s14p+"</td>"+ //10-14tahun P    
                                    //3
                            "<td valign='middle' align='center'>"+th15s19l+"</td>"+ //15 th L
                            "<td valign='middle' align='center'>"+th15s19p+"</td>"+ //15 th P
                            "<td valign='middle' align='center'>"+th20s24l+"</td>"+ //20 th L
                            "<td valign='middle' align='center'>"+th20s24p+"</td>"+ //20 th P
                            "<td valign='middle' align='center'>"+th25s29l+"</td>"+ //25
                            "<td valign='middle' align='center'>"+th25s29p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th30s34l+"</td>"+ //30
                            "<td valign='middle' align='center'>"+th30s34p+"</td>"+  
                            "<td valign='middle' align='center'>"+th35s39l+"</td>"+ //35
                            "<td valign='middle' align='center'>"+th35s39p+"</td>"+ 
                                    //4
                            "<td valign='middle' align='center'>"+th40s44l+"</td>"+
                            "<td valign='middle' align='center'>"+th40s44p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th45s49l+"</td>"+
                            "<td valign='middle' align='center'>"+th45s49p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th50s54l+"</td>"+
                            "<td valign='middle' align='center'>"+th50s54p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th55s59l+"</td>"+
                            "<td valign='middle' align='center'>"+th55s59p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th60s64l+"</td>"+
                            "<td valign='middle' align='center'>"+th60s64p+"</td>"+
                                    //5
                            "<td valign='middle' align='center'>"+th65s69l+"</td>"+
                            "<td valign='middle' align='center'>"+th65s69p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th70s74l+"</td>"+
                            "<td valign='middle' align='center'>"+th70s74p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th75s79l+"</td>"+
                            "<td valign='middle' align='center'>"+th75s79p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th80s84l+"</td>"+
                            "<td valign='middle' align='center'>"+th80s84p+"</td>"+ 
                            "<td valign='middle' align='center'>"+th85s100l+"</td>"+
                            "<td valign='middle' align='center'>"+th85s100p+"</td>"+
                                    //
                            "<td valign='middle' align='center'>"+(jam0s23l+hr1s7l+hr8s28l+hr29s3l+bl3s5l+bl6s11l+th1s4l+th5s9l+th10s14l+th15s19l+
                                    th20s24l+th25s29l+th30s34l+th35s39l+th40s44l+th45s49l+th50s54l+th55s59l+th60s64l+th65s69l+th70s74l+th75s79l+th80s84l+th85s100l)+"</td>"+
                            "<td valign='middle' align='center'>"+(jam0s23p+hr1s7p+hr8s28p+hr29s3p+bl3s5p+bl6s11p+th1s4p+th5s9p+th10s14p+th15s19p+
                                    th20s24p+th25s29p+th30s34p+th35s39p+th40s44p+th45s49p+th50s54p+th55s59p+th60s64p+th65s69p+th70s74p+th75s79p+th80s84p+th85s100p)+"</td>"+
                            "<td valign='middle' align='center'>"+(jam0s23p+jam0s23l+hr1s7p+hr1s7l+hr8s28p+hr8s28l+hr29s3p+hr29s3l+bl3s5p+bl3s5l+
                            bl6s11p+bl6s11l+th1s4p+th1s4l+th5s9l+th5s9p+th10s14l+th10s14p+th15s19l+th15s19p+
                            th20s24l+th20s24p+th25s29l+th25s29p+th30s34l+th30s34p+th35s39l+th35s39p+th40s44l+th40s44p+
                            th45s49l+th45s49p+th50s54l+th50s54p+th55s59l+th55s59p+th60s64l+th60s64p+th65s69l+th65s69p+
                            th70s74l+th70s74p+th75s79l+th75s79p+th80s84l+th80s84p+th85s100l+th85s100p-mati)+"</td>"+
                            "<td valign='middle' align='center'>"+mati+"</td>"+
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgRL4A.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML1.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgRL4A.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());        
    }
    
    
    
    public void isCek(){
        BtnPrint.setEnabled(akses.getrl4asebab());
    }
    
}
