
package bridging;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.apache.commons.codec.binary.Base64;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author dosen
 */
public final class DataLoincRestApi extends javax.swing.JDialog {

    private final DefaultTableModel tabMode, tabModeLocal;
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private Connection koneksi = koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i = 0, j = 0;
    private String json = "", auth, authEncrypt, combo;
    private ObjectMapper mapper = new ObjectMapper();
    private JsonNode root, nameNode, response;
    private int row;
    private HttpHeaders headers;
    private HttpEntity requestEntity;
    private ApiSatuSehat api = new ApiSatuSehat();
    private String userLoinc ="",passLoinc ="";
    

    /**
     * Creates new form DlgJnsPerawatanRalan
     *
     * @param parent
     * @param modal
     */
    public DataLoincRestApi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8, 1);
        try {
            userLoinc = koneksiDB.USERLOINC();
            passLoinc = koneksiDB.PASSWORDLOINC();
        } catch (Exception ex) {
            System.out.println("Notifikasi : "+ex);
        }
        tabModeLocal = new DefaultTableModel(null, new Object[]{
            "Code", "Long Component", "Component", "Property", "Timing", "System", "Scale", "Method", "UCUM"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbListLoincDataLocal.setModel(tabModeLocal);

        tbListLoincDataLocal.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbListLoincDataLocal.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 9; i++) {
            TableColumn column = tbListLoincDataLocal.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(100);
            } else if (i == 1) {
                column.setPreferredWidth(400);
            } else if (i == 2) {
                column.setPreferredWidth(300);
            } else if (i == 3) {
                column.setPreferredWidth(150);
            } else if (i == 4) {
                column.setPreferredWidth(150);
            } else if (i == 5) {
                column.setPreferredWidth(150);
            } else if (i == 6) {
                column.setPreferredWidth(150);
            } else if (i == 7) {
                column.setPreferredWidth(150);
            }
        }
        tbListLoincDataLocal.setDefaultRenderer(Object.class, new WarnaTable());
        tabMode = new DefaultTableModel(null, new Object[]{
            "Code", "Long Component", "Component", "Property", "Timing", "System", "Scale", "Method", "UCUM"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbListLoincData.setModel(tabMode);

        tbListLoincData.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbListLoincData.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 9; i++) {
            TableColumn column = tbListLoincData.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(100);
            } else if (i == 1) {
                column.setPreferredWidth(400);
            } else if (i == 2) {
                column.setPreferredWidth(300);
            } else if (i == 3) {
                column.setPreferredWidth(150);
            } else if (i == 4) {
                column.setPreferredWidth(150);
            } else if (i == 5) {
                column.setPreferredWidth(150);
            } else if (i == 6) {
                column.setPreferredWidth(150);
            } else if (i == 7) {
                column.setPreferredWidth(150);
            }
        }
        tbListLoincData.setDefaultRenderer(Object.class, new WarnaTable());

        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        TabPaneLoinc = new widget.TabPane();
        internalFrame3 = new widget.InternalFrame();
        Scroll1 = new widget.ScrollPane();
        tbListLoincDataLocal = new widget.Table();
        jPanel4 = new javax.swing.JPanel();
        panelGlass10 = new widget.panelisi();
        jLabel8 = new widget.Label();
        TCari1 = new widget.TextBox();
        BtnCari1 = new widget.Button();
        BtnKeluar1 = new widget.Button();
        jLabel9 = new widget.Label();
        LCount1 = new widget.Label();
        jLabel135 = new widget.Label();
        page1 = new widget.ComboBox();
        jLabel136 = new widget.Label();
        hal1 = new widget.ComboBox();
        internalFrame2 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbListLoincData = new widget.Table();
        jPanel3 = new javax.swing.JPanel();
        panelGlass9 = new widget.panelisi();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnKeluar = new widget.Button();
        jLabel7 = new widget.Label();
        LCount = new widget.Label();
        jLabel133 = new widget.Label();
        page = new widget.ComboBox();
        jLabel134 = new widget.Label();
        hal = new widget.ComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), ".:[ Data Loinc Rest Api ]:.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(1400, 587));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        TabPaneLoinc.setName("TabPaneLoinc"); // NOI18N

        internalFrame3.setName("internalFrame3"); // NOI18N
        internalFrame3.setLayout(new java.awt.BorderLayout());

        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        tbListLoincDataLocal.setAutoCreateRowSorter(true);
        tbListLoincDataLocal.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbListLoincDataLocal.setName("tbListLoincDataLocal"); // NOI18N
        tbListLoincDataLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListLoincDataLocalMouseClicked(evt);
            }
        });
        tbListLoincDataLocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbListLoincDataLocalKeyPressed(evt);
            }
        });
        Scroll1.setViewportView(tbListLoincDataLocal);

        internalFrame3.add(Scroll1, java.awt.BorderLayout.CENTER);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(44, 44));
        jPanel4.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass10.setName("panelGlass10"); // NOI18N
        panelGlass10.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel8.setText("Key Word :");
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass10.add(jLabel8);

        TCari1.setName("TCari1"); // NOI18N
        TCari1.setPreferredSize(new java.awt.Dimension(450, 23));
        TCari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCari1KeyPressed(evt);
            }
        });
        panelGlass10.add(TCari1);

        BtnCari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari1.setMnemonic('2');
        BtnCari1.setToolTipText("Alt+2");
        BtnCari1.setName("BtnCari1"); // NOI18N
        BtnCari1.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCari1ActionPerformed(evt);
            }
        });
        BtnCari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCari1KeyPressed(evt);
            }
        });
        panelGlass10.add(BtnCari1);

        BtnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar1.setMnemonic('K');
        BtnKeluar1.setText("Keluar");
        BtnKeluar1.setToolTipText("Alt+K");
        BtnKeluar1.setName("BtnKeluar1"); // NOI18N
        BtnKeluar1.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar1ActionPerformed(evt);
            }
        });
        BtnKeluar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluar1KeyPressed(evt);
            }
        });
        panelGlass10.add(BtnKeluar1);

        jLabel9.setText("Record :");
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(75, 23));
        panelGlass10.add(jLabel9);

        LCount1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount1.setText("0");
        LCount1.setName("LCount1"); // NOI18N
        LCount1.setPreferredSize(new java.awt.Dimension(80, 23));
        panelGlass10.add(LCount1);

        jLabel135.setText("Jumlah Data per Halaman");
        jLabel135.setName("jLabel135"); // NOI18N
        jLabel135.setPreferredSize(new java.awt.Dimension(156, 14));
        panelGlass10.add(jLabel135);

        page1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "50", "100", "200" }));
        page1.setName("page1"); // NOI18N
        page1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                page1ItemStateChanged(evt);
            }
        });
        page1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                page1KeyPressed(evt);
            }
        });
        panelGlass10.add(page1);

        jLabel136.setText("Halaman :");
        jLabel136.setName("jLabel136"); // NOI18N
        panelGlass10.add(jLabel136);

        hal1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        hal1.setName("hal1"); // NOI18N
        hal1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hal1ItemStateChanged(evt);
            }
        });
        hal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hal1KeyPressed(evt);
            }
        });
        panelGlass10.add(hal1);

        jPanel4.add(panelGlass10, java.awt.BorderLayout.PAGE_START);

        internalFrame3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        TabPaneLoinc.addTab("Local Data", internalFrame3);

        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setLayout(new java.awt.BorderLayout());

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbListLoincData.setAutoCreateRowSorter(true);
        tbListLoincData.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbListLoincData.setName("tbListLoincData"); // NOI18N
        tbListLoincData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListLoincDataMouseClicked(evt);
            }
        });
        tbListLoincData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbListLoincDataKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbListLoincData);

        internalFrame2.add(Scroll, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(44, 44));
        jPanel3.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass9.setName("panelGlass9"); // NOI18N
        panelGlass9.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass9.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(450, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass9.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnCari);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnKeluar);

        jLabel7.setText("Record :");
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(75, 23));
        panelGlass9.add(jLabel7);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(80, 23));
        panelGlass9.add(LCount);

        jLabel133.setText("Jumlah Data per Halaman");
        jLabel133.setName("jLabel133"); // NOI18N
        jLabel133.setPreferredSize(new java.awt.Dimension(156, 14));
        panelGlass9.add(jLabel133);

        page.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "50", "100", "200" }));
        page.setName("page"); // NOI18N
        page.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pageItemStateChanged(evt);
            }
        });
        page.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pageKeyPressed(evt);
            }
        });
        panelGlass9.add(page);

        jLabel134.setText("Halaman :");
        jLabel134.setName("jLabel134"); // NOI18N
        panelGlass9.add(jLabel134);

        hal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        hal.setName("hal"); // NOI18N
        hal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                halItemStateChanged(evt);
            }
        });
        hal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                halKeyPressed(evt);
            }
        });
        panelGlass9.add(hal);

        jPanel3.add(panelGlass9, java.awt.BorderLayout.PAGE_START);

        internalFrame2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        TabPaneLoinc.addTab("Loinc Server", internalFrame2);

        internalFrame1.add(TabPaneLoinc, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } else {

        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            BtnCari.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            BtnKeluar.requestFocus();
        }
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampilListLoinc(TCari.getText().trim());
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        } else {

        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void tbListLoincDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListLoincDataMouseClicked
        if (tabMode.getRowCount() != 0) {
            try {
                if (evt.getClickCount() == 2) {
                    Sequel.queryu4("insert into data_loinc values(?,?,?,?,?,?,?,?,?)", 9, new String[]{
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 0).toString(),
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 1).toString(),
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 2).toString(),
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 3).toString(),
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 4).toString(),
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 5).toString(),
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 6).toString(),
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 7).toString(),
                        tbListLoincData.getValueAt(tbListLoincData.getSelectedRow(), 8).toString(),});
                    dispose();
                }

            } catch (java.lang.NullPointerException e) {
            }
        }
}//GEN-LAST:event_tbListLoincDataMouseClicked

    private void tbListLoincDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListLoincDataKeyPressed
        if (tabMode.getRowCount() != 0) {
            if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {
                try {

                } catch (java.lang.NullPointerException e) {
                }
            }
        }
}//GEN-LAST:event_tbListLoincDataKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void pageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pageItemStateChanged
        tampilListLoincTotalRow(TCari.getText().trim());
    }//GEN-LAST:event_pageItemStateChanged

    private void pageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pageKeyPressed

    }//GEN-LAST:event_pageKeyPressed

    private void halItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_halItemStateChanged
        tampilListLoincPerPage(TCari.getText().trim());
    }//GEN-LAST:event_halItemStateChanged

    private void halKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_halKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_halKeyPressed

    private void tbListLoincDataLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListLoincDataLocalMouseClicked
        if (tabModeLocal.getRowCount() != 0) {
            try {
                if (evt.getClickCount() == 2) {
                    dispose();
                }
            } catch (java.lang.NullPointerException e) {
            }
        }
    }//GEN-LAST:event_tbListLoincDataLocalMouseClicked

    private void tbListLoincDataLocalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListLoincDataLocalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbListLoincDataLocalKeyPressed

    private void TCari1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCari1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCari1KeyPressed

    private void BtnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCari1ActionPerformed
        tampil();
    }//GEN-LAST:event_BtnCari1ActionPerformed

    private void BtnCari1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCari1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCari1KeyPressed

    private void BtnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar1ActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluar1ActionPerformed

    private void BtnKeluar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar1KeyPressed

    private void page1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_page1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_page1ItemStateChanged

    private void page1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_page1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_page1KeyPressed

    private void hal1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hal1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_hal1ItemStateChanged

    private void hal1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hal1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_hal1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DataLoincRestApi dialog = new DataLoincRestApi(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnCari1;
    private widget.Button BtnKeluar;
    private widget.Button BtnKeluar1;
    private widget.Label LCount;
    private widget.Label LCount1;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private widget.TextBox TCari;
    private widget.TextBox TCari1;
    private widget.TabPane TabPaneLoinc;
    private widget.ComboBox hal;
    private widget.ComboBox hal1;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame3;
    private widget.Label jLabel133;
    private widget.Label jLabel134;
    private widget.Label jLabel135;
    private widget.Label jLabel136;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label jLabel8;
    private widget.Label jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private widget.ComboBox page;
    private widget.ComboBox page1;
    private widget.panelisi panelGlass10;
    private widget.panelisi panelGlass9;
    private widget.Table tbListLoincData;
    private widget.Table tbListLoincDataLocal;
    // End of variables declaration//GEN-END:variables

    public JTable getTable() {
        if (TabPaneLoinc.getSelectedIndex() == 0) {
            return tbListLoincDataLocal;
        } else {
            return tbListLoincData;
        }

    }

    public void setSearch(String componen) {
        TCari.setText(componen);
    }

    public void tampilListLoinc(String componen) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        String halaman, offset;
        halaman = page.getSelectedItem().toString();
        int next = hal.getSelectedIndex();
        offset = (Integer.parseInt(halaman) * next) + "";
        Valid.tabelKosong(tabMode);
        auth = userLoinc+":"+passLoinc;
        byte[] encodedBytes = Base64.encodeBase64(auth.getBytes());
        authEncrypt = new String(encodedBytes);
        try {
            int hasil, total, perpage;
            headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.add("Authorization", "Basic " + authEncrypt);
            requestEntity = new HttpEntity(headers);
            root = mapper.readTree(api.getRest().exchange("https://loinc.regenstrief.org/searchapi/loincs?query=" + componen + "&rows=" + halaman + "&offset=" + offset + "&sortorder=loinc_num", HttpMethod.GET, requestEntity, String.class).getBody());
            LCount.setText(root.path("ResponseSummary").path("RecordsFound").asText());
            for (JsonNode list : root.path("Results")) {
                tabMode.addRow(new String[]{
                    list.path("LOINC_NUM").asText(), list.path("LONG_COMMON_NAME").asText(), list.path("COMPONENT").asText(),
                    list.path("PROPERTY").asText(), list.path("TIME_ASPCT").asText(), list.path("SYSTEM").asText(),
                    list.path("SCALE_TYP").asText(), list.path("METHOD_TYP").asText(), list.path("EXAMPLE_UCUM_UNITS").asText()
                });
                i++;
            }
            j = 1;
            total = Integer.parseInt(root.path("ResponseSummary").path("RecordsFound").asText());
            perpage = Integer.parseInt(page.getSelectedItem().toString());
            hasil = total / perpage;
            hal.removeAllItems();
            for (j = 1; j <= hasil; j++) {
                combo = "false";
                hal.addItem(j);
            }
            combo = "true";
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
        this.setCursor(Cursor.getDefaultCursor());
    }

    public void tampilListLoincTotalRow(String componen) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        String halaman, offset;
        halaman = page.getSelectedItem().toString();
        int next = hal.getSelectedIndex();
        offset = (Integer.parseInt(halaman) * next) + "";
        Valid.tabelKosong(tabMode);
        auth = userLoinc+":"+passLoinc;
        byte[] encodedBytes = Base64.encodeBase64(auth.getBytes());
        authEncrypt = new String(encodedBytes);
        try {
            int hasil, total, perpage;
            headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.add("Authorization", "Basic " + authEncrypt);
            requestEntity = new HttpEntity(headers);
            root = mapper.readTree(api.getRest().exchange("https://loinc.regenstrief.org/searchapi/loincs?query=" + componen + "&rows=" + halaman + "&offset=" + offset + "&sortorder=loinc_num", HttpMethod.GET, requestEntity, String.class).getBody());
//            System.out.println("response : " + root);
            LCount.setText(root.path("ResponseSummary").path("RecordsFound").asText());
            j = 1;
            total = Integer.parseInt(root.path("ResponseSummary").path("RecordsFound").asText());
            perpage = Integer.parseInt(page.getSelectedItem().toString());
            hasil = total / perpage;
            hal.removeAllItems();
            for (j = 1; j <= hasil; j++) {
                combo = "false";
                hal.addItem(j);
            }
            combo = "true";
            for (JsonNode list : root.path("Results")) {
                tabMode.addRow(new String[]{
                    list.path("LOINC_NUM").asText(), list.path("LONG_COMMON_NAME").asText(), list.path("COMPONENT").asText(),
                    list.path("PROPERTY").asText(), list.path("TIME_ASPCT").asText(), list.path("SYSTEM").asText(),
                    list.path("SCALE_TYP").asText(), list.path("METHOD_TYP").asText(), list.path("EXAMPLE_UCUM_UNITS").asText()
                });
                i++;
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
        this.setCursor(Cursor.getDefaultCursor());
    }

    public void tampilListLoincPerPage(String componen) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        String halaman;
        halaman = page.getSelectedItem().toString();
        int next = hal.getSelectedIndex();
        int offset = (Integer.parseInt(halaman) * next);
        if (offset >= 0 && combo.equals("true")) {
            Valid.tabelKosong(tabMode);
            auth = userLoinc+":"+passLoinc;
            byte[] encodedBytes = Base64.encodeBase64(auth.getBytes());
            authEncrypt = new String(encodedBytes);
            try {
                int hasil, total, perpage;
                headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                headers.add("Authorization", "Basic " + authEncrypt);
                requestEntity = new HttpEntity(headers);
                root = mapper.readTree(api.getRest().exchange("https://loinc.regenstrief.org/searchapi/loincs?query=" + componen + "&rows=" + halaman + "&offset=" + offset + "&sortorder=loinc_num", HttpMethod.GET, requestEntity, String.class).getBody());
                LCount.setText(root.path("ResponseSummary").path("RecordsFound").asText());
                for (JsonNode list : root.path("Results")) {
                    tabMode.addRow(new String[]{
                        list.path("LOINC_NUM").asText(), list.path("LONG_COMMON_NAME").asText(), list.path("COMPONENT").asText(),
                        list.path("PROPERTY").asText(), list.path("TIME_ASPCT").asText(), list.path("SYSTEM").asText(),
                        list.path("SCALE_TYP").asText(), list.path("METHOD_TYP").asText(), list.path("EXAMPLE_UCUM_UNITS").asText()
                    });
                    i++;
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            }
        }
        this.setCursor(Cursor.getDefaultCursor());
    }

    public void tampil() {
        Valid.tabelKosong(tabModeLocal);
        try {
            ps = koneksi.prepareStatement(
                    "select * "
                    + "from data_loinc where "
                    + "data_loinc.code like ? or data_loinc.component like ?  order by code ASC");
            try {
                ps.setString(1, "%" + TCari1.getText() + "%");
                ps.setString(2, "%" + TCari1.getText() + "%");
                rs = ps.executeQuery();
                while (rs.next()) {
                    tabModeLocal.addRow(new Object[]{
                        rs.getString("code"), rs.getString("long_component"), rs.getString("component"),
                        rs.getString("property"), rs.getString("timing"), rs.getString("system"), rs.getString("scale"),
                        rs.getString("method")
                    });
                }
            } catch (Exception e) {
                System.out.println("Notif Loinc Data : " + e);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
        LCount1.setText("" + tabModeLocal.getRowCount());
    }
}
