/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package simrskhanza;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author perpustakaan
 */
public class DlgDataPasien extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;

    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
    public DlgDataPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(885,674);
        
    }

    //private DlgCariObatPenyakit dlgobtpny=new DlgCariObatPenyakit(null,false);
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TNoRW = new widget.TextBox();
        TNoRM = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        FormInput = new widget.PanelBiasa();
        Alamat = new widget.TextBox();
        jLabel9 = new widget.Label();
        jLabel10 = new widget.Label();
        JK = new widget.TextBox();
        jLabel11 = new widget.Label();
        Tempat = new widget.TextBox();
        jLabel12 = new widget.Label();
        Tanggal = new widget.TextBox();
        NamaPasien = new widget.TextBox();
        jLabel13 = new widget.Label();
        Agama = new widget.TextBox();
        jLabel15 = new widget.Label();
        Prov = new widget.TextBox();
        jLabel16 = new widget.Label();
        Kota = new widget.TextBox();
        jLabel17 = new widget.Label();
        Kec = new widget.TextBox();
        jLabel18 = new widget.Label();
        Kel = new widget.TextBox();
        jLabel19 = new widget.Label();
        HP = new widget.TextBox();
        jLabel20 = new widget.Label();
        Email = new widget.TextBox();
        jLabel21 = new widget.Label();
        Pekerjaan = new widget.TextBox();
        jLabel22 = new widget.Label();
        Nikah = new widget.TextBox();
        jLabel23 = new widget.Label();
        Pendidikan = new widget.TextBox();
        jLabel24 = new widget.Label();
        NmIbu = new widget.TextBox();
        PngJwb = new widget.TextBox();
        jLabel26 = new widget.Label();
        Keluarga = new widget.TextBox();
        jLabel27 = new widget.Label();
        Suku = new widget.TextBox();
        jLabel25 = new widget.Label();
        NIK = new widget.TextBox();
        jLabel28 = new widget.Label();
        BPJS = new widget.TextBox();
        panelGlass8 = new widget.panelisi();
        BtnKeluar = new widget.Button();

        TNoRW.setEditable(false);
        TNoRW.setHighlighter(null);
        TNoRW.setName("TNoRW"); // NOI18N
        TNoRW.setPreferredSize(new java.awt.Dimension(155, 24));

        TNoRM.setHighlighter(null);
        TNoRM.setName("TNoRM"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Data Pasien ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput.setLayout(null);

        Alamat.setHighlighter(null);
        Alamat.setName("Alamat"); // NOI18N
        Alamat.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Alamat);
        Alamat.setBounds(80, 70, 680, 23);

        jLabel9.setText("JK: ");
        jLabel9.setName("jLabel9"); // NOI18N
        FormInput.add(jLabel9);
        jLabel9.setBounds(520, 10, 50, 23);

        jLabel10.setText("Agama:");
        jLabel10.setName("jLabel10"); // NOI18N
        FormInput.add(jLabel10);
        jLabel10.setBounds(630, 10, 37, 23);

        JK.setHighlighter(null);
        JK.setName("JK"); // NOI18N
        JK.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(JK);
        JK.setBounds(570, 10, 50, 23);

        jLabel11.setText("Nama Lengkap:");
        jLabel11.setName("jLabel11"); // NOI18N
        FormInput.add(jLabel11);
        jLabel11.setBounds(-20, 10, 100, 23);

        Tempat.setHighlighter(null);
        Tempat.setName("Tempat"); // NOI18N
        Tempat.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Tempat);
        Tempat.setBounds(390, 40, 150, 23);

        jLabel12.setText("No BPJS:");
        jLabel12.setName("jLabel12"); // NOI18N
        FormInput.add(jLabel12);
        jLabel12.setBounds(20, 220, 60, 23);

        Tanggal.setHighlighter(null);
        Tanggal.setName("Tanggal"); // NOI18N
        Tanggal.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Tanggal);
        Tanggal.setBounds(540, 40, 110, 23);

        NamaPasien.setHighlighter(null);
        NamaPasien.setName("NamaPasien"); // NOI18N
        NamaPasien.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(NamaPasien);
        NamaPasien.setBounds(80, 10, 470, 23);

        jLabel13.setText("No KTP/ NIK:");
        jLabel13.setName("jLabel13"); // NOI18N
        FormInput.add(jLabel13);
        jLabel13.setBounds(-20, 40, 100, 23);

        Agama.setHighlighter(null);
        Agama.setName("Agama"); // NOI18N
        Agama.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Agama);
        Agama.setBounds(670, 10, 90, 23);

        jLabel15.setText("Alamat:");
        jLabel15.setName("jLabel15"); // NOI18N
        FormInput.add(jLabel15);
        jLabel15.setBounds(-20, 70, 100, 23);

        Prov.setHighlighter(null);
        Prov.setName("Prov"); // NOI18N
        Prov.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Prov);
        Prov.setBounds(80, 100, 130, 23);

        jLabel16.setText("Penanggung Jawab:");
        jLabel16.setName("jLabel16"); // NOI18N
        FormInput.add(jLabel16);
        jLabel16.setBounds(250, 190, 100, 23);

        Kota.setHighlighter(null);
        Kota.setName("Kota"); // NOI18N
        Kota.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Kota);
        Kota.setBounds(260, 100, 210, 23);

        jLabel17.setText("Kota:");
        jLabel17.setName("jLabel17"); // NOI18N
        FormInput.add(jLabel17);
        jLabel17.setBounds(220, 100, 40, 23);

        Kec.setHighlighter(null);
        Kec.setName("Kec"); // NOI18N
        Kec.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Kec);
        Kec.setBounds(550, 100, 160, 23);

        jLabel18.setText("Kecamatan:");
        jLabel18.setName("jLabel18"); // NOI18N
        FormInput.add(jLabel18);
        jLabel18.setBounds(490, 100, 60, 23);

        Kel.setHighlighter(null);
        Kel.setName("Kel"); // NOI18N
        Kel.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Kel);
        Kel.setBounds(80, 130, 130, 23);

        jLabel19.setText("Provinsi:");
        jLabel19.setName("jLabel19"); // NOI18N
        FormInput.add(jLabel19);
        jLabel19.setBounds(-20, 100, 100, 23);

        HP.setHighlighter(null);
        HP.setName("HP"); // NOI18N
        HP.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(HP);
        HP.setBounds(80, 160, 120, 23);

        jLabel20.setText("No HP:");
        jLabel20.setName("jLabel20"); // NOI18N
        FormInput.add(jLabel20);
        jLabel20.setBounds(-20, 160, 100, 23);

        Email.setHighlighter(null);
        Email.setName("Email"); // NOI18N
        Email.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Email);
        Email.setBounds(240, 160, 120, 23);

        jLabel21.setText("Email:");
        jLabel21.setName("jLabel21"); // NOI18N
        FormInput.add(jLabel21);
        jLabel21.setBounds(210, 160, 30, 23);

        Pekerjaan.setHighlighter(null);
        Pekerjaan.setName("Pekerjaan"); // NOI18N
        Pekerjaan.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Pekerjaan);
        Pekerjaan.setBounds(430, 160, 130, 23);

        jLabel22.setText("Pekerjaan:");
        jLabel22.setName("jLabel22"); // NOI18N
        FormInput.add(jLabel22);
        jLabel22.setBounds(330, 160, 100, 23);

        Nikah.setHighlighter(null);
        Nikah.setName("Nikah"); // NOI18N
        Nikah.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Nikah);
        Nikah.setBounds(470, 130, 120, 23);

        jLabel23.setText("Status Nikah:");
        jLabel23.setName("jLabel23"); // NOI18N
        FormInput.add(jLabel23);
        jLabel23.setBounds(370, 130, 100, 23);

        Pendidikan.setHighlighter(null);
        Pendidikan.setName("Pendidikan"); // NOI18N
        Pendidikan.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Pendidikan);
        Pendidikan.setBounds(640, 160, 70, 23);

        jLabel24.setText("Pendidikan:");
        jLabel24.setName("jLabel24"); // NOI18N
        FormInput.add(jLabel24);
        jLabel24.setBounds(580, 160, 60, 23);

        NmIbu.setHighlighter(null);
        NmIbu.setName("NmIbu"); // NOI18N
        NmIbu.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(NmIbu);
        NmIbu.setBounds(80, 190, 160, 23);

        PngJwb.setHighlighter(null);
        PngJwb.setName("PngJwb"); // NOI18N
        PngJwb.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(PngJwb);
        PngJwb.setBounds(350, 190, 70, 23);

        jLabel26.setText("Nama Ibu:");
        jLabel26.setName("jLabel26"); // NOI18N
        FormInput.add(jLabel26);
        jLabel26.setBounds(20, 190, 60, 23);

        Keluarga.setHighlighter(null);
        Keluarga.setName("Keluarga"); // NOI18N
        Keluarga.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Keluarga);
        Keluarga.setBounds(420, 190, 210, 23);

        jLabel27.setText("Kelurahan:");
        jLabel27.setName("jLabel27"); // NOI18N
        FormInput.add(jLabel27);
        jLabel27.setBounds(20, 130, 60, 23);

        Suku.setHighlighter(null);
        Suku.setName("Suku"); // NOI18N
        Suku.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(Suku);
        Suku.setBounds(260, 130, 120, 23);

        jLabel25.setText("Tempat /Tanggal Lahir:");
        jLabel25.setName("jLabel25"); // NOI18N
        FormInput.add(jLabel25);
        jLabel25.setBounds(240, 40, 150, 23);

        NIK.setHighlighter(null);
        NIK.setName("NIK"); // NOI18N
        NIK.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(NIK);
        NIK.setBounds(80, 40, 180, 23);

        jLabel28.setText("Suku:");
        jLabel28.setName("jLabel28"); // NOI18N
        FormInput.add(jLabel28);
        jLabel28.setBounds(200, 130, 60, 23);

        BPJS.setHighlighter(null);
        BPJS.setName("BPJS"); // NOI18N
        BPJS.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(BPJS);
        BPJS.setBounds(80, 220, 200, 23);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);
        FormInput.getAccessibleContext().setAccessibleName("");
        FormInput.getAccessibleContext().setAccessibleDescription("");

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(100, 56));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Tutup");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TNoRM.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgDataPasien dialog = new DlgDataPasien(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.TextBox Agama;
    private widget.TextBox Alamat;
    private widget.TextBox BPJS;
    private widget.Button BtnKeluar;
    private widget.TextBox Email;
    private widget.PanelBiasa FormInput;
    private widget.TextBox HP;
    private widget.TextBox JK;
    private widget.TextBox Kec;
    private widget.TextBox Kel;
    private widget.TextBox Keluarga;
    private widget.TextBox Kota;
    private widget.TextBox NIK;
    private widget.TextBox NamaPasien;
    private widget.TextBox Nikah;
    private widget.TextBox NmIbu;
    private widget.TextBox Pekerjaan;
    private widget.TextBox Pendidikan;
    private widget.TextBox PngJwb;
    private widget.TextBox Prov;
    private widget.TextBox Suku;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRW;
    private widget.TextBox Tanggal;
    private widget.TextBox Tempat;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel11;
    private widget.Label jLabel12;
    private widget.Label jLabel13;
    private widget.Label jLabel15;
    private widget.Label jLabel16;
    private widget.Label jLabel17;
    private widget.Label jLabel18;
    private widget.Label jLabel19;
    private widget.Label jLabel20;
    private widget.Label jLabel21;
    private widget.Label jLabel22;
    private widget.Label jLabel23;
    private widget.Label jLabel24;
    private widget.Label jLabel25;
    private widget.Label jLabel26;
    private widget.Label jLabel27;
    private widget.Label jLabel28;
    private widget.Label jLabel9;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables
    

    private void isPsien() {
        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ",NamaPasien,TNoRM.getText());
        Sequel.cariIsi("select pasien.jk from pasien where pasien.no_rkm_medis=? ",JK,TNoRM.getText());
        Sequel.cariIsi("select pasien.agama from pasien where pasien.no_rkm_medis=? ",Agama,TNoRM.getText());
        Sequel.cariIsi("select pasien.tgl_lahir from pasien where pasien.no_rkm_medis=? ",Tanggal,TNoRM.getText());
        Sequel.cariIsi("select pasien.tmp_lahir from pasien where pasien.no_rkm_medis=? ",Tempat,TNoRM.getText());
        Sequel.cariIsi("select pasien.no_ktp from pasien where pasien.no_rkm_medis=? ",NIK,TNoRM.getText());
        Sequel.cariIsi("select pasien.alamat from pasien where pasien.no_rkm_medis=? ",Alamat,TNoRM.getText());
        Sequel.cariIsi("select pasien.nm_ibu from pasien where pasien.no_rkm_medis=? ",NmIbu,TNoRM.getText());
        Sequel.cariIsi("select pasien.pekerjaan from pasien where pasien.no_rkm_medis=? ",Pekerjaan,TNoRM.getText());
        Sequel.cariIsi("select pasien.stts_nikah from pasien where pasien.no_rkm_medis=? ",Nikah,TNoRM.getText());
        Sequel.cariIsi("select pasien.no_tlp from pasien where pasien.no_rkm_medis=? ",HP,TNoRM.getText());
        Sequel.cariIsi("select pasien.pnd from pasien where pasien.no_rkm_medis=? ",Pendidikan,TNoRM.getText());
        Sequel.cariIsi("select pasien.keluarga from pasien where pasien.no_rkm_medis=? ",PngJwb,TNoRM.getText());
        Sequel.cariIsi("select pasien.namakeluarga from pasien where pasien.no_rkm_medis=? ",Keluarga,TNoRM.getText());
        Sequel.cariIsi("select pasien.no_peserta from pasien where pasien.no_rkm_medis=? ",BPJS,TNoRM.getText());
        Sequel.cariIsi("select pasien.email from pasien where pasien.no_rkm_medis=? ",Email,TNoRM.getText());
        Sequel.cariIsi("select suku_bangsa.nama_suku_bangsa from pasien inner join suku_bangsa on suku_bangsa.id=pasien.suku_bangsa where pasien.no_rkm_medis=? ",Suku,TNoRM.getText());
        Sequel.cariIsi("select kelurahan.nm_kel from pasien inner join kelurahan on kelurahan.kd_kel=pasien.kd_kel where pasien.no_rkm_medis=? ",Kel,TNoRM.getText());
        Sequel.cariIsi("select kecamatan.nm_kec from pasien inner join kecamatan on kecamatan.kd_kec=pasien.kd_kec where pasien.no_rkm_medis=? ",Kec,TNoRM.getText());
        Sequel.cariIsi("select kabupaten.nm_kab from pasien inner join kabupaten on kabupaten.kd_kab=pasien.kd_kab where pasien.no_rkm_medis=? ",Kota,TNoRM.getText());
        Sequel.cariIsi("select propinsi.nm_prop from pasien inner join propinsi on propinsi.kd_prop=pasien.kd_prop where pasien.no_rkm_medis=? ",Prov,TNoRM.getText());
        
    }

    public void setNoRm(String norm,String norawat) {
        TNoRM.setText(norm); 
        TNoRW.setText(norawat);
        isPsien();         
    }
    
    
    public void isCek(){
       
        
    }



}
